name: Deploy Backend to EC2

on:
  push:
    branches:
      - deploy/cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          
          sudo su

          cd /Meet-Your-Books

          git sparse-checkout init --cone
          git sparse-checkout set BE
          git fetch origin deploy/cicd
          git checkout deploy/cicd
          git pull origin deploy/cicd

          cd BE

          pm2 restart app

          pm2 list

          EOF
