name: 'Deploy Frontend'

on:
  push:
    branches:
      - deploy/cicd

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FE
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            ./FE

      - name: Create .env.production file
        run: |
          echo "VITE_KAKAO_URL=${{ secrets.VITE_KAKAO_URL }}" > .env.production
          echo "VITE_KAKAO_REST_API_KEY=${{ secrets.VITE_KAKAO_REST_API_KEY }}" > .env.production
          echo "VITE_KAKAO_JAVASCRIPT_API_KEY=${{ secrets.VITE_KAKAO_JAVASCRIPT_API_KEY }}" >> .env.production
          echo "VITE_AUTH_REDIRECT_URL=${{ secrets.VITE_AUTH_REDIRECT_URL }}" >> .env.production
          echo "VITE_BACK_END_API_URL=${{ secrets.VITE_BACK_END_API_URL }}" >> .env.production

      - name: Check Node version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete

      - name: CloudFront Cache Invalidation
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"
